### ISSUE TITLE
As a teacher, I want to create and store grading rubrics to ensure consistent grading.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#1]
**Acceptance criteria**
- [x] Rubric integration into CASMM

**Tasks**
- [x] Create rubric section in AssignmentEditor Modal
- [x] Store rubric in database
- [x] Create student view for stored rubric
- [x] Extensive UI and unit testing

**Comment by lyndseylaborde** [comment]
![Image](https://github.com/CEN3031-F23-Group4c/sapphire-project04-4c/assets/100553983/7fb41998-aed0-4cff-9c58-c563a0a828b1)

**Comment by lyndseylaborde** [comment]
Updates:
Static rubric implemented and styled
Backend integration in progress

Next steps:
Complete functionality
Add rubric creation to Content Creator role
