### ISSUE TITLE
As a student, I want to receive immediate feedback after submitting my code to know if my solution is correct or needs improvement.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#11]
**Acceptance criteria**
- [x] A student gets automatic feedback from the submit button

**Tasks**
- [x] A popup appears when a student clicks submit explaining their grade
- [x] The grade value in the server is edited on submit

**Comment by calebreverett** [comment]
Implemented pretty fully, just needs to be integrated with the feedback system.
