### ISSUE TITLE
As a teacher, I want to send feedback directly to individual students so they understand their mistakes and learn from them.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#2]
**Acceptance criteria**
- [x] A feedback system is implemented
- [x] Feedback feature is available to students
- [ ] A grades page showcases the students grade and feedback

**Tasks**
- [x] Create individual student assignment pages based off existing Researcher pages (for Teacher viewing only)
- [x] Add comment box to individual student assignment pages (for Teacher viewing only)
- [x] Store comments on both student and teacher side in database
- [x] Display a message to the student when their teacher has provided feedback
- [x] Allow the student to view all feedback left by their teacher (may be multiple comments)
- [x] Display all provided feedback on the teacher side
- [x] Extensive UI testing

**Comment by jonathanwuki** [comment]
Updates:
- Much of the frontend functionality has been implemented; however, all of the functionality that is intended for the teacher currently resides in the researcher role. This is due to the fact that I couldn't get Strapi Admin to load without crashing the entire backend, so I couldn't move around any permissions from researcher -> teacher.

Next Steps:
- Resolve issue with Strapi Admin crash to access backend and move researcher functionality to teacher role
- Link up the frontend and backend to fetch teacher comments for each assignment (instead of hardcoding them)

**Comment by jonathanwuki** [comment]
**Post-Sprint 2 Updates:**
- All frontend functionality has been implemented. Unfortunately, Strapi is still non-functional so the project currently uses local browser storage for feedback items. I believe a Strapi update is necessary to make this work properly (as it is currently many major versions behind) but that is out of the scope of this particular project.
- I completed extensive UI testing by resizing the browser window and ensuring everything showed up normally, testing with long comments, short comments, whitespace only, etc.

**Next Steps:**
- None.
