### ISSUE TITLE
As a teacher, I want the system to automatically grade programs based on a pre-defined solution and test cases so that I can save time in grading numerous submissions.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#3]
**Acceptance Criteria**
- [x] Automatic grading is implemented that allows for test cases and code comparison.

**Tasks**
- [x] Create a backend process for automatic grading - Sprint 1
- [x] Implement a frontend access point in order to compare and grade code - Sprint 1
- [x] Create a more robust AutoGrade system instead of just string comparison - Sprint 2
- [x] Have the AutoGrade actually affect the student's grade - Sprint 2

**Comment by calebreverett** [comment]
Implemented minimally, but not implemented to the full extent with test cases and a better AutoGrade. Tested to make sure it is free of any obvious bugs with current CASMM implementation.

**Comment by calebreverett** [comment]
Implemented fully, just needs to be integrated to other solutions.
