### ISSUE TITLE
As a student, I want a page where I can view all my grades and feedback in one place.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#4]
**Acceptance criteria**
- [ ] A grades page showcases the students grade and feedback

**Tasks**
- [ ] Fetch grades from each individual student assignment
- [ ] Create table and display grades on dedicated page (student side)
- [ ] Extensive UI and unit testing
