### ISSUE TITLE
As a teacher, I want the ability to manually override the automatic grades in cases where alternate solutions are presented.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#5]
**Acceptance criteria**
- [ ] Has the ability to manually override the grades

**Tasks**
- [ ] Add grade text box to teacher assignment page
- [ ] Save manual grade
- [ ] Extensive UI and unit testing
