### ISSUE TITLE
As a student, I want to know if my code compiles successfully before submitting to avoid losing marks for syntax errors.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#6]
**Acceptance criteria**
- [ ] Students can test before submission and receive immediate results

**Tasks**
- [x] Utilize existing compilation system to separate serial functionality
- [ ] Automatically compile on student submission
- [x] Display compilation results to student
- [ ] Extensive UI and unit testing

**Comment by mikedami** [comment]
Currently being worked on, in progress
