### ISSUE TITLE
As a student, I want to receive personalized feedback from my teacher to improve my coding skills.

### ISSUE THREAD

**Issue by jonathanwuki** [CEN3031-F23-Group4c/sapphire-project04-4c#9]
**Acceptance criteria**
- [x] A feedback system is implemented
- [x] Feedback feature is available to students
- [ ] A grades page showcases the students grade and feedback

**Tasks**
- [x] Store comments on both student and teacher side in database
- [x] Display a message to the student when their teacher has provided feedback
- [x] Allow the student to view all feedback left by their teacher (may be multiple comments)
- [x] Extensive UI testing

**Comment by jonathanwuki** [comment]
**Post-Sprint 2 Updates:**
- All frontend functionality has been implemented. Unfortunately, Strapi is still non-functional so the project currently uses local browser storage for feedback items. I believe a Strapi update is necessary to make this work properly (as it is currently many major versions behind) but that is out of the scope of this particular project.
- I completed extensive UI testing by resizing the browser window and ensuring everything showed up normally, testing with long comments, short comments, whitespace only, etc.

**Next Steps:**
- None.
